# Generated by Django 4.1.1 on 2022-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_tagline', models.TextField(blank=True, max_length=300, null=True)),
                ('organization_vision', models.TextField(blank=True, max_length=300, null=True)),
                ('organization_mission', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_logo', models.ImageField(blank=True, default='', null=True, upload_to='organization/')),
                ('organization_is_active', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=200)),
                ('established_date', models.CharField(blank=True, max_length=200, null=True)),
                ('company_type', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
