# Generated by Django 4.1.1 on 2022-10-12 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import organizations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grouphead_type', models.CharField(choices=[(1, 'Technical'), (2, 'Non-Technical')], max_length=200)),
                ('is_status', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=1)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200, unique=True)),
                ('organization_tagline', models.TextField(blank=True, max_length=300, null=True)),
                ('organization_vision', models.TextField(blank=True, max_length=300, null=True)),
                ('organization_mission', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_logo', models.ImageField(blank=True, default='', null=True, upload_to=organizations.models.upload_to)),
                ('organization_is_active', models.BooleanField(default=1)),
                ('established_date', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_type', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_title', models.CharField(max_length=200)),
                ('department_description', models.TextField(blank=True, max_length=500, null=True)),
                ('department_status', models.BooleanField(default=1)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grouphead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.grouphead')),
            ],
        ),
        migrations.CreateModel(
            name='StaffClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_title', models.CharField(blank=True, max_length=200, null=True)),
                ('non_technical_title', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(default='auto title', max_length=200)),
                ('level', models.IntegerField(default=1)),
                ('is_status', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(blank=True, max_length=200, null=True)),
                ('position_description', models.TextField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('department_status', models.BooleanField(default=1)),
                ('salary_range', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(1)])),
                ('job_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('qualification_level', models.CharField(blank=True, max_length=200, null=True)),
                ('user_experience', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationdepartment')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.staffclassification')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('city_name', models.CharField(max_length=200)),
                ('latitute', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitute', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('is_head_office', models.BooleanField(default=0)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='grouphead',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
