# Generated by Django 4.1.1 on 2022-10-06 08:55

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=organizations.models.upload_to),
        ),
    ]
