# Generated by Django 4.1.1 on 2022-10-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouphead',
            name='is_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='staffclassification',
            name='is_status',
            field=models.IntegerField(default=1),
        ),
    ]
