# Generated by Django 4.1.1 on 2022-10-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='orgnaization_type',
            new_name='organization_type',
        ),
    ]
