# Generated by Django 4.1.1 on 2022-10-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouphead',
            old_name='org',
            new_name='organization',
        ),
    ]
