# Generated by Django 4.1.1 on 2022-10-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationlocation_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationlocation',
            name='city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
