# Generated by Django 4.1.1 on 2022-10-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_staffclassification_organizationposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffclassification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
