# Generated by Django 4.1.1 on 2022-09-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hrmsusers',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='hrmsusers',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
